[package]
name = "raptorq"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
raptorq = "1.8.1"

[build-dependencies]
cbindgen = "0.14.0"